<a href="https://colab.research.google.com/github/alchemistklk/pytorch_tutorial/blob/master/00_pytorch_fundmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.2.1+cu121'

## Introduction to Tensors
### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# the dimention equals the number of square brackets
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8]
                       ,[9, 10]])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 3, 5]
                        ,[2, 4, 6]
                        , [3, 6, 9]]])
TENSOR

tensor([[[1, 3, 5],
         [2, 4, 6],
         [3, 6, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 3, 5],
        [2, 4, 6],
        [3, 6, 9]])

### Random Tensors
Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of number then adjust those random numbers to better represent the data.
Crux of deep learning
`random data -> look at data -> update random numbers -> look at data -> update random numbers`
Torch random tensors:

In [ ]:
# Creating a random tensor of size(3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.3987, 0.2139, 0.2003, 0.3163],
         [0.2526, 0.0673, 0.7217, 0.6954],
         [0.6862, 0.2140, 0.4969, 0.1486]],

        [[0.9319, 0.8105, 0.8587, 0.4542],
         [0.0280, 0.4079, 0.9013, 0.7508],
         [0.8389, 0.1453, 0.3676, 0.3354]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([2, 3, 4])

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange(), you want a range of number
one_to_ten = torch.arange(1, 10, 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating tensor with same shape
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype
**Note:** Tensor type is one one 3 big errors you'll run into with Pytorch & deep learning
1. Tensors not right datatyoe
2. Tensors not right shape
3. Tensors not on the right device
Precision in computing:
todo:

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what type is the tensor
                               device=None,# what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Covert the datatype of tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
varibale = float_16_tensor * float_32_tensor
varibale.dtype

torch.float32

### Getting information from tensors
1. Tensor not right datatype - to get datatype from a tensor, use `tensor.dtype`
2. Tensor not right shape - to get datatype from a tensor, use `tensor.shape`
3. Tensor not on thr right device - to get device from a tensor, use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6933, 0.3853, 0.9863, 0.7598],
        [0.6639, 0.2382, 0.0982, 0.3992],
        [0.4451, 0.2196, 0.2093, 0.8918]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of some_tensor is {some_tensor.dtype}")
print(f"Shape of some_tensor is {some_tensor.shape}")
print(f"device tensor is on {some_tensor.device}")

tensor([[0.6933, 0.3853, 0.9863, 0.7598],
        [0.6639, 0.2382, 0.0982, 0.3992],
        [0.4451, 0.2196, 0.2093, 0.8918]])
Datatype of some_tensor is torch.float32
Shape of some_tensor is torch.Size([3, 4])
device tensor is on cpu


### Manipulating Tensors(tensor operations)
Tensor operation includes:
- Addition
- Substraction
- Multiplication(element-wise)
- Division
- Matrix multiplication


In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
# Addition
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Substraction
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication
Two main way of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication(dot product)



There are two main rules that performing matrix multiplication need to satisfy
1. The **inner dimensions** must match
  - (3, 2) @ (3, 2) won't work
  - (3, 2) @ (2, 3) will work
  - (2, 3) @ (3, 2) will work
2. The resulting matrix has a shape of **outer dimensions**
  - (2, 3) @ (3, 2) -> (2, 2)



In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 2.28 ms, sys: 48 µs, total: 2.33 ms
Wall time: 9.31 ms


tensor(14)

In [ ]:
# tensor_A = torch.rand(2, 3)
# tensor_B = torch.rand(2, 3)
# print(f"matmul result: {tensor_A @ tensor_B}")

In [ ]:
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)
print(f"matmul result: {tensor_A @ tensor_B.T}")
output = torch.matmul(tensor_A, tensor_B.T)
print(f"The shape of resulting matrix: {output.size()}")

matmul result: tensor([[1.2284, 1.6164],
        [0.9416, 1.2266]])
The shape of resulting matrix: torch.Size([2, 2])


### Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
x.type(torch.float32 ).mean()

tensor(45.)

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the positional in tensor that minimal value with argmin() -> returns index postion of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, viewing, stacking
- Reshaping - reshape an input tensor to a define shape
- View - Return a view of an input tensor of certain shape but **keep the same memory as the original tensor**
- Stacking - combine multiple tensors as top of each other(vstack) or side by side (hstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a cerain way

In [ ]:
x = torch.arange(1, 10)
x.shape

torch.Size([9])

In [ ]:
x_reshaped = x.reshape(3, 3)
x_reshaped = x.reshape(1, 9)

In [ ]:
# Change the view
# Change z changes x (because a view of a tensor shares the same memory as the orginal memory)
z = x_reshaped.view(1, 9)
z[:, 0] = 5
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Stack tensors on the top of each other
# vstack dim = 0; vstack dim = 1
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

### Squeezing, unsqueezing, permuting
  - Squeezing: Returns a tensor with all specificed dimentions of `input` of size 1 removed
  - Unsqueezing: Returns a new tensor with a dimension of size one inserted in specific position.
  - Permute: Returns a view of originla tensor input with its dimensions permuted

In [ ]:
# torch.squeeze() - remove all single dimension from a target tensor
print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeeze = x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeeze}")
print(f"New shape: {x_squeeze.shape}")

Previous tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor:tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [ ]:
print(f"Previous tensor: {x_reshaped.squeeze()}")
print(f"Previous shape: {x_reshaped.squeeze().shape}")

x_unsqueeze = x_reshaped.unsqueeze(dim = 0)
print(f"New tensor: {x_unsqueeze}")
print(f"New shape: {x_unsqueeze.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]])
New shape: torch.Size([1, 1, 9])


In [ ]:
# Rearrange the dimension of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3))
x_permute = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permute.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing(Selecting data from tensors)
Indexing with Pytorch is similar to indexing with Numpy

In [ ]:
x_index = torch.arange(1, 10).reshape(1, 3, 3)
x_index
print(x_index[0][0][0])
print(x_index)

tensor(1)
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
# You can use the ":" to select "all" of a target dimension
x_index[:,:, 0]

tensor([[1, 4, 7]])

### Pytorch tensors & NumPy
NumPy is a popular scentific Python numerical computing library
Because of this, Pytorch has functionality to interact with it
  - Data in NumPy, want in Pytorch tensor -> `torch.from_numpy()`
  - Pytorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
array.dtype

dtype('float64')

In [ ]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

### Reproducbility(trying to take random out of random)
In short how a neutal network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation -> again`

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**
Essentially what the random seed does is "flavour" the randomness


In [ ]:
MANUAL_SEED = 42
torch.manual_seed(MANUAL_SEED)
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(MANUAL_SEED)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and Pytorch objects on the GPU(and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make every hunkydory

#### 1. Check GPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

#### 2. Putting tensors(and models) on GPU
The reason why we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_gpu = tensor.to(device)
print(tensor_gpu, tensor_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


#### 3. Use CPU to calculate

In [ ]:
tensor_gpu.cpu().numpy()

array([1, 2, 3])