<a href="https://colab.research.google.com/github/alchemistklk/pytorch_tutorial/blob/master/00_pytorch_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.Documentation reading
- "torch.Tensor": A tensor is a `multi-dimensional matrix` containing elements of a single data type
- "torch.cuda": It implements the same function as a CPU tensors, but they utilize GPUs for computation.

### 2. Create a random tensor with shape(7,7)

In [ ]:
import torch
rand_ten_2 = torch.rand(7, 7)
print(rand_ten_2)

tensor([[0.1161, 0.6627, 0.9236, 0.5959, 0.6162, 0.3945, 0.3277],
        [0.0830, 0.0552, 0.3471, 0.2469, 0.6715, 0.6746, 0.5701],
        [0.7161, 0.5779, 0.3435, 0.2205, 0.5691, 0.9369, 0.7056],
        [0.7673, 0.3652, 0.2207, 0.1355, 0.7274, 0.5910, 0.9010],
        [0.6606, 0.9261, 0.7152, 0.2504, 0.9545, 0.6715, 0.8092],
        [0.6454, 0.2499, 0.5733, 0.4655, 0.3382, 0.5928, 0.9529],
        [0.0924, 0.6448, 0.0552, 0.7330, 0.5621, 0.2889, 0.3650]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape(1, 7)

In [ ]:
rand_ten_3 = torch.rand(1, 7)
multi_res = torch.matmul(rand_ten_2, rand_ten_3.T)
print(multi_res)
print(multi_res.size())
print(multi_res.shape)

tensor([[2.2185],
        [1.5521],
        [1.9967],
        [1.8663],
        [2.6334],
        [2.1708],
        [1.5463]])
torch.Size([7, 1])
torch.Size([7, 1])


### 4. Set the random seed to 0 and do 2 & 3 again

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_ten_4_1 = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
rand_ten_4_2 = torch.rand(1, 7)
matmul_res_4 = torch.matmul(rand_ten_4_1, rand_ten_4_2.T)
print(matmul_res_4)

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?

In [ ]:
GPU_MANUAL_SEED = 1234
torch.cuda.manual_seed(GPU_MANUAL_SEED)

### 6. Create two random tensor of shape(2, 3) and send them both to the GPU

In [ ]:
torch.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_6_1 = torch.rand(2, 3).to(device)
torch.manual_seed(42)
tensor_6_2 = torch.rand(2, 3).to(device)
print(f"Device: {device}")
print(tensor_6_1, tensor_6_1.device)
print(tensor_6_2, tensor_6_2.device)

Device: cuda
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0') cuda:0
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0') cuda:0


### 7. Perform a matrix multiplication on the tensors you created in 6

In [ ]:
matmul_res_7 = torch.matmul(tensor_6_1, tensor_6_2.T)
print(matmul_res_7)

tensor([[1.7622, 1.4337],
        [1.4337, 1.4338]], device='cuda:0')


In [ ]:
### 8. Find the maximum and minimum values of the output of 7
max = torch.max(matmul_res_7)
min = torch.min(matmul_res_7)
max, min

(tensor(1.7622, device='cuda:0'), tensor(1.4337, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7

In [ ]:
max_index = torch.argmax(matmul_res_7)
min_index = torch.argmin(matmul_res_7)
print(max_index)
print(min_index)

tensor(0, device='cuda:0')
tensor(1, device='cuda:0')


### 10. Make a random tensor with shape (1, 1, 1, 7) and then create a new tensor with all 1 dimensions removed to be left with a shape of (10)

In [ ]:
torch.manual_seed(7)
tensor_10 = torch.rand(1, 1, 1, 7)
print(tensor_10, tensor_10.shape)
new_tensor_10 = tensor_10.squeeze()
print(new_tensor_10, new_tensor_10.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]]]]) torch.Size([1, 1, 1, 7])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]) torch.Size([7])
